name = "React Router"
roles = ["frontend", "backend"]
webhooks_path = "/webhooks/app/uninstalled"

[commands]
predev = "npx --no-install prisma generate"
dev = "npx --no-install prisma db push && npm exec react-router dev"
